server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: reservas-hotel-api

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=HotelReservasDB;encrypt=true;trustServerCertificate=true;
    username: sa
    password: 2026@app!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE